from __future__ import annotations

COMPARABLE = "COMPARABLE"
NOT_COMPARABLE = "NOT_COMPARABLE"

CROSS_SOLVER_SIDE_NOT_VERIFIED = "CROSS_SOLVER_SIDE_NOT_VERIFIED"
CROSS_SOLVER_ROLE_MISMATCH = "CROSS_SOLVER_ROLE_MISMATCH"
CROSS_SOLVER_QUERY_MISMATCH = "CROSS_SOLVER_QUERY_MISMATCH"
CROSS_SOLVER_UNIT_UNKNOWN = "CROSS_SOLVER_UNIT_UNKNOWN"
CROSS_SOLVER_UNIT_MISMATCH = "CROSS_SOLVER_UNIT_MISMATCH"
CROSS_SOLVER_REFERENCE_FRAME_MISMATCH = "CROSS_SOLVER_REFERENCE_FRAME_MISMATCH"
CROSS_SOLVER_METRIC_UNAVAILABLE = "CROSS_SOLVER_METRIC_UNAVAILABLE"
CROSS_SOLVER_OPERATION_NOT_SUPPORTED = "CROSS_SOLVER_OPERATION_NOT_SUPPORTED"

__all__ = [
    "COMPARABLE",
    "CROSS_SOLVER_METRIC_UNAVAILABLE",
    "CROSS_SOLVER_OPERATION_NOT_SUPPORTED",
    "CROSS_SOLVER_QUERY_MISMATCH",
    "CROSS_SOLVER_REFERENCE_FRAME_MISMATCH",
    "CROSS_SOLVER_ROLE_MISMATCH",
    "CROSS_SOLVER_SIDE_NOT_VERIFIED",
    "CROSS_SOLVER_UNIT_MISMATCH",
    "CROSS_SOLVER_UNIT_UNKNOWN",
    "NOT_COMPARABLE",
]
