from __future__ import annotations

ROLE_TYPES = frozenset(
    {
        "TOWER_BASE",
        "GIRDER_END",
        "BEARING",
        "DAMPER_ATTACHMENT",
        "MIDSPAN",
        "SUPPORT",
    }
)

RESOLVED = "RESOLVED"
UNRESOLVED = "UNRESOLVED"
INVALID = "INVALID"
STALE_MODEL = "STALE_MODEL"

STATICALLY_CONFIRMED = "STATICALLY_CONFIRMED"
NOT_STATICALLY_ENUMERABLE = "NOT_STATICALLY_ENUMERABLE"

__all__ = [
    "INVALID",
    "NOT_STATICALLY_ENUMERABLE",
    "RESOLVED",
    "ROLE_TYPES",
    "STALE_MODEL",
    "STATICALLY_CONFIRMED",
    "UNRESOLVED",
]
